### ISSUE TITLE
bug: random failure of test `test_get_logs_address`

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#1097]
# Bug Report

**Kakarot RPC version:**

**Current behavior:**
The test sometimes randomly fails in the CI on 
 https://github.com/kkrt-labs/kakarot-rpc/blob/25f8cf4694a316703231cdc6a400546d8de8cd81/tests/tests/eth_provider.rs#L344-L346

**Expected behavior:**
The test should pass everytime.

**Steps to reproduce:**
This is the main issue: reproducing locally as proven very difficult, as running the test 10+ times failed to expose the issue. 
Might have to just run it locally multiple times with logging of the DB until the issue arises.

For this:
- Add logging of the test fill of the database.
- Build the genesis `make katana-genesis`.
- Un-ignore the test `test_get_logs_address`.
- Run the specific test `make test-target TARGET= test_get_logs_address`.
- Repeat previous step until test fails.
- Study logs in order to find issue.

**Comment by rvalenciano** [comment]
Hey, can I take an attempt on this one?

**Comment by greged93** [comment]
it's not really a `good first issue` @rvalenciano so it might be complicated

**Comment by rvalenciano** [comment]
@greged93 I'll try to reproduce the issue and ping here if I'm able to find anything.

**Comment by rvalenciano** [comment]
@greged93 giving an update, I was able to reproduce the issue by running

```bash
for i in 1 2 3 4 5 6 7 8 9 10
do
   RUST_BACKTRACE=1 make test-target TARGET=test_get_logs_address
done
```

Working on a solution.

**Comment by rvalenciano** [comment]
Hey @greged93 , got a question. I determine that the random failures is because of random data, specifically the numbers that we use for the block_number on the ETH Logs. Here we can see a comparison of the filter used in the MongoDB of a failed test in the left, and a successful test in the right.

<img width="1338" alt="Screenshot 2024-06-04 at 22 28 41" src="https://github.com/kkrt-labs/kakarot-rpc/assets/5366444/c374a91c-9c0c-42e7-aefb-cf7fdbc91ed2">

As you can see, the block number in the failing test is bigger than the `to` value of the filter. In the successful test, this is not the case, which makes the MongoDB filter to return logs, as opposed as the initial case where no logs are returned because the block number is bigger than the `to` value of the filter.

<img width="409" alt="Screenshot 2024-06-04 at 22 28 31" src="https://github.com/kkrt-labs/kakarot-rpc/assets/5366444/ba620c33-70d5-4994-8fab-d900cf201a22">

Now that we have determined the cause of the random failure, we need to determine how to fix it.

1. First, we generate a collection of Logs that we store in a MongoDB collection. The values of the `block_number`, determined [here](https://github.com/rvalenciano/kakarot-rpc/blob/65d1208522f4df5734ea75b635faa7c38d1ce7cf/src/eth_provider/database/types/log.rs#L37), is just a an arbitrary u64.

2. The value of the `to`  value comes or from this [function](https://github.com/rvalenciano/kakarot-rpc/blob/0beba46412cf3f7035df1c0947d7c789b46ad63b/src/eth_provider/provider.rs#L412), which seems to be defined in this crate: `alloy_rpc_types::eth::filter`.

Since the possible value of `block_number` is the maximum possible value of a u64, and block_number should never be bigger than the `to` value, at least for the purpose of filtering logs on this test, to make it deterministic, should `to` always be the max value of a u64? 

For the purpose of the test, can we mock the value than the `to` value is returning to make sure is in range of the filter?

Or should we make a dynamic assertion depending of the value of `to` ?

**Comment by greged93** [comment]
Hey @rvalenciano thanks a lot for you work in debugging this! I think for now you can just use `u64::MAX` as the value of `to` in the block range. You can update the tests `test_get_logs_topics`, `test_get_logs_block_range` and `test_get_logs_address` to fix this (I think the test `test_get_logs_block_hash` is fine since if doesn't use the block range). Again thanks!
