### ISSUE TITLE
dev: refactor txpool rpc tests 

### ISSUE THREAD

**Issue by tcoratger** [kkrt-labs/kakarot-rpc#1108]
### Describe the enhancement request

Currently, in the tx pool rpc tests, there are quite a few duplications in the construction of the tests. This can be observed in the following file:

https://github.com/kkrt-labs/kakarot-rpc/blob/main/tests/tests/txpool_api.rs

To avoid this repetition and improve the maintainability of the test suite, we propose to refactor the test content by introducing test utilities. These utilities can be built at the beginning of the file and then reused across different tests, leading to cleaner and more concise test code.

### Proposed Changes

1. **Create Test Utilities:**
   - Develop reusable functions and structures that encapsulate common setup and teardown logic for the tx pool tests.
   - Place these utilities at the beginning of the `txpool_api.rs` file for easy access.

2. **Refactor Existing Tests:**
   - Replace repetitive code in the current tests with calls to the new test utilities.
   - Ensure that each test remains clear and focused on its specific logic, leveraging the utilities for shared setup.

Related https://github.com/kkrt-labs/kakarot-rpc/pull/1105#discussion_r1611080943

**Comment by Gerson2102** [comment]
Hey, can you assign me this issue?

**Comment by Gerson2102** [comment]
I'm working on this issue. And I'm getting a linker error with clang. I had deal with this kind of errors months ago, they are really anoying.

This is the error:

````
error: linking with `clang` failed: exit status: 254
= note: clang: error: unable to execute command: Killed
          clang: error: linker command failed due to signal (use -v to see invocation)
````

And this is my config.toml:

```
# [target.x86_64-unknown-linux-gnu]
# linker = "x86_64-linux-gnu-gcc"

# [target.aarch64-unknown-linux-gnu]
# linker = "aarch64-linux-gnu-gcc"
# /usr/bin/mold
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]
```
Right now I'm using mold, because i had the same problem when i was setting up the cairo native project and madara project. And using mold, fixed the issue, but with kakarot-rpc it seems that is not working this solution :(

I'm getting the error because I'm trying to see if the test that i was modifying is working properly.

**Comment by greged93** [comment]
mmmm I am not familiar with this issue, what is the command you are running?

**Comment by Gerson2102** [comment]
@greged93 
I'm using WSL Ubuntu. And when I run `cargo build` I'm getting that error. I know that error is because WSL while compiling is running out of memory, I have dealt with this in Cairo Native and Madara. And in those projects what I did to fix it, I added this:

![image](https://github.com/kkrt-labs/kakarot-rpc/assets/71728860/c997ee93-fcf0-4762-99bb-6430f3873563)

I tried to do the same for this project, and is not working :(
