### ISSUE TITLE
[URGENT] gemba: review the nonce management strategy for the relayer fleet [3]

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#1502]
**Describe the enhancement request**

During Tech strategy meeting, review nonce management strategy with @ClementWalter 

after v0.7.5 fixes, we are still observing strong occurrences of "failed to relay transactions" errors in the RPC. This suggests nonces in the relayer fleet are still subject to falling out of sync a lot, cf:
<img width="1505" alt="image" src="https://github.com/user-attachments/assets/dd2fee92-3396-45d9-a570-fd59ecb069fb">
Where we see in the "logs occurence" dozens of nonce errors.

**Comment by greged93** [comment]
In order to reduce the nonce errors, the final decision is to call Starknet each time to get the relayer nonce before sending the transaction and to remove the local nonce handling.

Investigate as well a way to "lock" the relayer for as long as we don't receive Starknet's status of the transaction.
