### ISSUE TITLE
Refactor `KakarotTestEnvironmentContext` to access the state directly

### ISSUE THREAD

**Issue by ftupas** [kkrt-labs/kakarot-rpc#560]
In some parts of the codebase, we are doing `sequencer.sequencer` or `sequencer().sequencer` to access the state, for example:

https://github.com/kkrt-labs/kakarot-rpc/blob/51803e63497bef3d8a7f4f45efb97d6084b8a09c/crates/hive-utils/src/madara/utils.rs#L407

We should refactor the implementation of `KakarotTestEnvironmentContext` to access this directly

**Comment by bajpai244** [comment]
Fred, I can take this.

**Comment by bajpai244** [comment]
@ftupas so I am not sure whether this refactor is needed.

If look at the definition of the test_seqeuncer:
```rust
pub struct TestSequencer {
    url: Url,
    handle: NodeHandle,
    account: TestAccount,
    pub sequencer: Arc<KatanaSequencer>,
}
```

So, if we are { or would be } interested in other fields like { URL, or the Account }, then we should keep the current implementation we have. This comes because of design from a third party crate, and I think it is fine for it to be in this way!

Lemme know what you think about it?

**Comment by ftupas** [comment]
Indeed we're accessing the other fields, however we might be able to provide getters directly to avoid doing `sequencer().sequencer` to get the backend state

```rust
let sequencer = test_context.sequencer();
let dump_state = sequencer
    .sequencer
    .backend
    .state
    .blocking_write()
    .dump_state()
    .expect("Failed to call dump_state on Katana state");
```
